name       : python-audioread
version    : 3.0.0
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/a/audioread/audioread-3.0.0.tar.gz : 121995bd207eb1fda3d566beb851d3534275925bc35a4fb6da0cb11de0f7251a
homepage   : https://github.com/beetbox/audioread
license    : MIT
component  : programming.python
summary    : multi-library, cross-platform audio decoding
description: |
    cross-library (GStreamer + Core Audio + MAD + FFmpeg) audio decoding for Python
builddeps  :
    - python-build
    - python-installer
build      : |
    %python3_setup
install    : |
    %python3_install
